name: kakao
repository: https://github.com/chatbot-pf/chatbot-mobile

packages:
  - packages/**

ignore:
  - "package/**/*example"
  - "package/kakao_map"

scripts:
  pub:get_all:
    run: |
      melos run pub:get --no-select

  pub:get:
    run: |
      melos exec -c 1 -- "flutter pub get"
    select-package: