include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/src/messages.dart"
    - "lib/src/test.dart"
  errors:
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning